"use client";
import { SpeedInsights } from "@vercel/speed-insights/next";
import type { Metadata } from "next";
import { Bungee, Fira_Sans, Inter, Righteous, Jura } from "next/font/google";
import "./globals.css";

import { useEffect } from "react";
import { AuthContextProvider } from "../context/AuthContext";
import Navtop from "../components/Navtop";

const bungee = Righteous({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-bungee",
});
const fira = Jura({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-fira",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${bungee.variable} ${fira.variable}`}>
      <body className="bg-white">
        <AuthContextProvider>
          <Navtop />
          {children}
        </AuthContextProvider>

        <SpeedInsights />
      </body>
    </html>
  );
}
