import type { Metadata } from "next";
import { Bungee, Fira_Sans, Inter } from "next/font/google";
import "./globals.css";

const bungee = Bungee({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-bungee",
});
const fira = Fira_Sans({
  subsets: ["latin"],
  weight: ["400", "900", "700"],
  variable: "--font-fira",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${bungee.variable} ${fira.variable}`}>
      <body>{children}</body>
    </html>
  );
}
